### ISSUE TITLE
Note deletions aren't being synced between devices

### ISSUE THREAD

**Issue by Terrance** [laurent22/joplin#10689]
### Operating system

Windows

### Joplin version

3.0.12 (Windows), 3.0.7 (Android)

### Desktop version info

```
Joplin 3.0.12 (prod, win32)

Client ID: 2ca5a676b7954ae89721faa06464e5e6
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: a64d6e3

Backup: 1.4.1
Cursor Sync: 2.1.0
Joplin Calendar: 1.2.0
Joplin Note Attachement rename: 1.2.2
Kanban: 1.0.7
Note overview: 1.7.1
Outline: 1.5.13
```

```
Joplin 3.0.7 (prod, android)

Client ID: d8e98c66054049f0b59e6d8c0db590b2
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Joplin Calendar: 1.2.0
Outline: 1.5.13

Android API level: 33
WebView version: 126.0.6478.134
WebView package: com.google.android.webview
FTS enabled: 1
Hermes enabled: 1
```

### Current behaviour

1. Delete a note on either platform, sending it to the new Trash folder.
2. Ensure this client is synced.
3. Ensure the other client is synced.
   * Note remains in its original location on the other client.
   * Note can be deleted independently on other clients.

### Expected behaviour

Notes to be moved to the corresponding Trash folder on other devices after a sync.

### Logs

Android log just before initiating a sync that includes a deletion from Windows:

```
Date,Level,Message
07-06T10:46:36,30,RevisionService: maintenance: Done in 387ms
07-06T10:46:36,30,RevisionService: collectRevisions: Created revisions for 1 notes
07-06T10:46:35,30,root: root.biometrics: shouldShowMainContent <true>
07-06T10:46:35,30,"root: root.biometrics: this.state.sensorInfo {""enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}"
07-06T10:46:35,30,root: root.biometrics: biometricsDone <true>
07-06T10:46:35,30,root: root.biometrics: biometricsEnabled <false>
07-06T10:46:35,30,RevisionService: maintenance: Starting...
07-06T10:46:35,30,RevisionService: maintenance: Service is enabled
07-06T10:44:16,30,SearchEngine: Updated FTS table in 235ms. Inserted: 0. Deleted: 0
07-06T10:44:16,30,"Updating items_normalized from {""updated_time":0,"id":""}"
07-06T10:44:16,30,SearchEngine: Updating FTS table...
07-06T10:44:15,30,DecryptionWorker: cannot start because no master key is currently loaded.
07-06T10:44:14,30,root: root.biometrics: biometricsDone <true>
07-06T10:44:14,30,root: root.biometrics: biometricsEnabled <false>
07-06T10:44:14,30,root: root.biometrics: shouldShowMainContent <true>
07-06T10:44:14,30,"root: root.biometrics: this.state.sensorInfo {""enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}"
07-06T10:44:14,30,checkDisabledSyncItemsNotification: No errors: Hiding notification
07-06T10:44:14,30,Synchronizer: Total folders: 24
07-06T10:44:14,30,Synchronizer: Total notes: 3276
07-06T10:44:14,30,Synchronizer: Total resources: 43
07-06T10:44:14,30,Synchronizer: fetchingTotal: 1
07-06T10:44:14,30,Synchronizer: fetchingProcessed: 1
07-06T10:44:14,30,Synchronizer: Operations completed: 
07-06T10:44:14,30,Synchronizer: Sync: finished: Synchronisation finished [1720259054027]
07-06T10:44:14,30,"ShareService: Refreshed shares: {""items":[],"has_more":false}"
07-06T10:44:14,30,ShareService: Refresh share invitations: []
07-06T10:44:14,30,Synchronizer: Sync: fetchingProcessed: Processing fetched item
07-06T10:44:14,30,Synchronizer: supportsDeltaWithItems =  <true>
07-06T10:44:14,30,Synchronizer: Sync: fetchingTotal: Fetching delta items from sync target
07-06T10:44:14,30,Synchronizer: TaskQueue.stop: syncDownload: waiting for tasks to complete: 0
07-06T10:44:14,30,"Synchronizer: TaskQueue.stop: syncDownload: Done, waited for 0"
07-06T10:44:14,30,"Synchronizer: Sync target local info: {""version":3,"e2ee":{"value":false,"updatedTime":0},"activeMasterKeyId":{"value":"","updatedTime":0},"masterKeys":[],"ppk":{"value":null,"updatedTime":0},"appMinVersion":"3.0.0"}"
07-06T10:44:14,30,"Synchronizer: Sync target remote info: {""version":3,"e2ee":{"value":false,"updatedTime":0},"activeMasterKeyId":{"value":"","updatedTime":0},"masterKeys":[],"ppk":{"value":null,"updatedTime":0},"appMinVersion":"3.0.0"}"
07-06T10:44:14,30,Synchronizer: Sync target is already setup - checking it...
07-06T10:44:14,30,ResourceService::indexNoteResources: Completed
07-06T10:44:14,30,Synchronizer: Indexing resources...
07-06T10:44:14,30,ResourceService::indexNoteResources: Start
07-06T10:44:14,30,Synchronizer: Sync: starting: Starting synchronisation to target 9... supportsAccurateTimestamp = true; supportsMultiPut = true} [1720259054027]
07-06T10:44:14,30,root: root.biometrics: biometricsDone <true>
07-06T10:44:14,30,root: root.biometrics: biometricsEnabled <false>
07-06T10:44:14,30,root: root.biometrics: shouldShowMainContent <true>
07-06T10:44:14,30,"root: root.biometrics: this.state.sensorInfo {""enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}"
07-06T10:44:14,30,Starting scheduled sync
07-06T10:44:14,30,Preparing scheduled sync
```

**Comment by personalizedrefrigerator** [comment]
I haven't managed to reproduce this. Here's what I've tried:
1. Synced the desktop and mobile clients (Joplin Cloud)
2. Deleted an existing note on the desktop client.
3. Synced the desktop client.
4. Synced the mobile client.
5. Checked the trash folder on the mobile client.
6. Observed the just-deleted note in the trash.
7. Restored the note on the mobile client.
8. Synced the mobile client, then the desktop client.

<details><summary>Version info</summary>

Desktop:
```
Joplin 3.0.12 (prod, linux)

Client ID: 24b2a961cccf40fe8448cdc0930b6fce
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: a64d6e327

Backup: 1.4.1
CodeMirror 6 settings: 1.0.0
Freehand Drawing: 2.11.0
Joplin debug tool: 0.2.0
RevealJS Integration: 0.14.0
Work tracker: 0.0.1
```

iOS (TestFlight version):
```
Joplin 13.0.3 (prod, ios)

Client ID: bd7dceef9c634159837b31252daa8fc9
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Quick Links: 1.3.2

iOS version: 17.5.1
FTS enabled: 1
Hermes enabled: 1
```

</details>

**Note**: I have end-to-end encryption enabled.

What sync target are you using? Do you have end-to-end encryption enabled? Do deletions sync if items are deleted from different folders (e.g. is it just one folder that deletions aren't syncing in?).

Thank you for reporting this!

**Comment by Terrance** [comment]
I'm using a self-hosted Joplin Server (2.14.2 which I believe is still the latest?) for sync, and not using end-to-end encryption.

As far as I can tell, deletions don't seem to be tracked from any of my note folders.  After deleting or undeleting a note, both clients report "Updated local items: 1. Fetched items: 1/1." during sync.

**Comment by MM2forever** [comment]
+1
I do have the same effect since my update to 3.x.x.x
I was still running Joplin Server 2.12.2 and updated it just now to test but to no avail, deletions are not synced for me as well.

Edit: Empyting the trash however syncs the deletion, but this is not expected behaviour.

**Comment by pedr** [comment]
This bug is fixed on new versions of Joplin Server, but a new docker image wasn't be released yet.

@laurent22 
I wonder if we couldn't automate the release of new docker images to avoid this problem in the future (the last one is 2.14.2, 6 months old)

**Comment by rextroumbley** [comment]
I'm experiencing the same issue on the docker version 2.14.2 of Joplin Server syncing between two Windows PCs and an Android phone. Thank you @pedr and @laurent22, for looking into it. Hopefully the docker images can be updated soon.

**Comment by Terrance** [comment]
I'm curious how the server is the problem...  I thought all of the sync targets were effectively simple file stores, with the clients doing all the work -- does the server process soft-deletes somehow?

**Comment by pedr** [comment]
I've reproduced this bug when running Joplin Server 2.14.2 (latest docker image available) and with clients on 3.0.x. The property `deleted_time` seems to be set to `0` when the note is synchronized between clients. I'm trying to investigate why that is happening since this property should only be used by the client anyway.


Desktop version: 
```
Joplin 3.0.13 (dev, linux)

Client ID: 73042e9329c141c1bb3ca0b38682edfd
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 24954bd0f (dev)

Backup: 1.4.1
```

Mobile version:
```
Joplin 3.0.8 (dev, android)

Client ID: 3fe1e755b3c74ac6add1815fac2374f0
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Android API level: 34
WebView version: 113.0.5672.119
WebView package: com.google.android.webview
FTS enabled: 1
Hermes enabled: 1
```

**Comment by pedr** [comment]
I think I understand now why this is happening:

On the server we are using a `removeUnknownFields` method that removes anything that isn't included in the specific class before saving the content of the item on the database:

![image](https://github.com/user-attachments/assets/a3331506-abcc-489c-9567-175e4e53cbac)

![image](https://github.com/user-attachments/assets/5fdc46e5-f9ed-4d59-bf02-7ee7475f0047)

So, I guess that in the 2.14.2 server version we didn't had a `deleted_time` property in the `/lib/Notes` class model which meant that notes that are sent to the Trash are saving the property, but in the synchronization we are removing it before being saved inside the `item` table on Joplin Server.

Edit: note sure if it is super clear but it is at this point where the content loses the property:
![image](https://github.com/user-attachments/assets/2ff9a884-5727-4185-ad3c-90c93a7bc096)

This happens when the `api/items` receives the PUT method, so that is why the content is saved without the property in the database.

@laurent22 
One solution would be to create a PR to include this new field to the `Note` class but it seems a little unnecessary since it is a somewhat old version of the server.

**Comment by Terrance** [comment]
For forwards compatibility, would it not be better to just leave unknown fields alone?

I'm still unclear how much involvement the server has in parsing notes -- presumably none when using E2EE, so I was assuming no involvement regardless, but I guess not given the above.  If it does care about the fields then the server should also probably honour/enforce some kind of schema version compatibility?  (Is that what "Sync Version" is?)

**Comment by rextroumbley** [comment]
The 3.0.1 update of Joplin Server did not, unfortunately, fix the deletion sync issue.

**Comment by pedr** [comment]
@rextroumbley 
Can you give me more information on which versions the devices are running and the steps to reproduce it?
I tested with Android 3.0.9 and Desktop 3.0.14 and it is working on my machine

**Comment by rextroumbley** [comment]
I'm also using Android 3.0.9, and Desktop 3.0.14 on a desktop and laptop PC, with Joplin Server 3.0.1. New notes sync across all three devices without issue, but deleted notes are only removed from the other two devices after the trash is emptied on the device where the note was originally deleted. Thanks again for your help.

**Comment by pedr** [comment]
Ah, ok, that makes sense, thanks for the help rextroumbley. The notes sent to trash before updating the server version won't be able to update their location because they are already synchronized. 

I know it is annoying, but I think the only way to fix this is emptying the trash or restoring the note and deleting it again (this should fix the problem, the note doesn't need to be new, but it should be deleted and synchronized by Joplin Server >3.0.1.

**Comment by rextroumbley** [comment]
Thanks, @pedr. When I experimented with syncing deleting notes on a fresh server and two desktop installs, notes I deleted on one desktop would disappear from the other desktop. However, when I tried re-syncing my original note collection using a fresh server installation, any notes I delete (new or previous) still do not sync between my devices. 

Would something about the type or number of notes in my database possibly cause the issue? Very odd. For now, I will just have to remember to empty the trash on each device before syncing. Thanks again for your help.

**Comment by Terrance** [comment]
I'm also still not seeing the Trash folder working correctly here after updates (Server 3.0.1, Windows 3.0.14, Android 3.0.7).

I don't currently have a second desktop to test if desktop-to-desktop sync works correctly, but neither of desktop-initiated or phone-initiated soft-deletes are making it across to the other device.  Permanently deleting a note does remove it from the other device (whether currently in Trash or not) though.

**Comment by Terrance** [comment]
Catching up on old issues, I don't think this has been a problem for some time now -- can probably close?
