### ISSUE TITLE
German-language text is present even when English (USA) is set

### ISSUE THREAD

**Issue by kmanwar89** [laurent22/joplin#11186]
### Operating system

macOS

### Joplin version

3.0.15

### Desktop version info

Joplin 3.0.15 (prod, darwin)

Client ID: c495bd23859c4307bbeb1379012169f1
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 598677b

Backup: 1.4.1

### Current behaviour

On a fresh installation of Joplin, the "backup plugin" is enabled by default. For some unknown reason, this plugin displays the following German-language text, even when the localization is set to English (USA):

Dieser Pfad ist exklusiv für die Joplin Backups, es sollten sich keine anderen Daten darin befinden, wenn die Einstellungen für 'Unterordner erstellen' deaktiviert wird!

Screenshot showing the menu in question:

![image](https://github.com/user-attachments/assets/5788598c-0477-4808-b2ee-b30e322e614c)

### Expected behaviour

Not display any non-English text when English is set as the application language

**Comment by JackGruber** [comment]
This is fixed in the Backup Plugin v1.4.2 https://github.com/JackGruber/joplin-plugin-backup/issues/74

But the Build in Version in Joplin is at the moment 1.4.1

**Comment by personalizedrefrigerator** [comment]
Joplin 3.1.17 includes v1.4.2 of the Backup Plugin. Based on the release cycle, [Joplin 3.1.17 should be released soon](https://joplinapp.org/help/about/release_cycle).

**Comment by kmanwar89** [comment]
> Joplin 3.1.17 includes v1.4.2 of the Backup Plugin. Based on the release cycle, [Joplin 3.1.17 should be released soon](https://joplinapp.org/help/about/release_cycle).

Thank you @personalizedrefrigerator! I checked the [release notes](https://github.com/laurent22/joplin/releases/tag/v3.1.17) but saw no mention of this bug being fixed in that version?

I confirmed the bug is still present on my Windows machine with Joplin 3.0.15.  After upgrading to 3.1.24, I can confirm the behavior is no longer present.
