### ISSUE TITLE
Trying to Sync to Joplin Server Beta (selfhosted) Leads to Endless Synchronization Loop

### ISSUE THREAD

**Issue by jonmchan** [laurent22/joplin#12029]
### Operating system

Windows

### Joplin version

Joplin Server v3.3.3

### Desktop version info

3.2.13

### Current behaviour

When the password is incorrect in the synchronization settings and when a sync is attempted, the synchronization button spins indefinitely:

![Image](https://github.com/user-attachments/assets/30b6560a-9c15-4714-a550-bded86560141)

### Expected behaviour

I would believe the expected behavior is to complete the request and display an error that the username and password is incorrect.

**Comment by laurent22** [comment]
Is there anything in the log? https://joplinapp.org/debugging

**Comment by jonmchan** [comment]
Error: Invalid username or password
Code: 403
Error: Invalid username or password

as expected. It just goes on and on and on.

[log.txt](https://github.com/user-attachments/files/19523712/log.txt)

**Comment by laurent22** [comment]
It's hard to tell from this sample of log file but does it really get stuck or is it just very slow? The fact that it retries multiple times is expected, but eventually it should display a message that the username and password needs to be checked. I've just tried locally and it's working like this.

**Comment by jonmchan** [comment]
How long is the `eventually it should display a message that the username and password needs to be checked`?

**Comment by jonmchan** [comment]
Here is a 15+ minute recording of it just looping endlessly.

https://www.dropbox.com/scl/fi/kpapwqhiqs16uzms8qsa7/Screen-Recording-2025-03-30-223834.mp4?rlkey=kwwqcki1y5fiqmsllhh6tovys&st=fduzd1vm&dl=0

I believe I found more accurate repro steps:

1. Be in a good synchronization state. The username and password should work and syncing should be working.
2. Shutdown the client - completely turn it off including in the tray.
3. Change the password from the web GUI.
4. Turn back on the client and it gets in the loop.

If that doesn't reproduce it for you, then I have to investigate more. 

I am also able to reproduce the expected invalid username and password status that doesn't infinitely sync if I change the password while the app is on.

![Image](https://github.com/user-attachments/assets/48b97376-26cf-4a55-a5a6-f00376a0a65d)


Here are the repro steps for that:

1. Be in a good synchronization state. The username and password should work and syncing should be working.
2. SKIP shutting down the client.
3. Change the password from the web GUI.
4. The next sync results in the screenshot above.

**Comment by laurent22** [comment]
Thanks for the additional information but even with these steps I still can't replicate this issue. I wonder if something is throttling the connection on error on your server?

What happens in the server log while you try to sync? Does it display very slowly failed http requests? If you could maybe share that log here too that could help

**Comment by jonmchan** [comment]
The server logs don't seem to show anything suspicious... 

When the proper error shows up, it looks like this:

```
joplin-1  | 02:44:02 0|app  | 2025-04-01 02:44:02: [error] App: 403: POST /api/sessions: 192.168.60.13: Invalid username or password: {"email":"jon***@gmail.com"}
joplin-1  | 02:44:02 0|app  | 2025-04-01 02:44:02: App: POST /api/sessions (403) (65ms)
joplin-1  | 02:44:02 0|app  | 2025-04-01 02:44:02: [error] App: 403: POST /api/sessions: 192.168.60.13: Invalid username or password: {"email":"jon***@gmail.com"}
joplin-1  | 02:44:02 0|app  | 2025-04-01 02:44:02: App: POST /api/sessions (403) (62ms)
joplin-1  | 02:44:02 0|app  | 2025-04-01 02:44:02: [error] App: 403: POST /api/sessions: 192.168.60.13: Invalid username or password: {"email":"jon***@gmail.com"}
joplin-1  | 02:44:02 0|app  | 2025-04-01 02:44:02: App: POST /api/sessions (403) (60ms)
joplin-1  | 02:44:02 0|app  | 2025-04-01 02:44:02: [error] App: 403: POST /api/sessions: 192.168.60.13: Invalid username or password: {"email":"jon***@gmail.com"}
joplin-1  | 02:44:02 0|app  | 2025-04-01 02:44:02: App: POST /api/sessions (403) (61ms)
joplin-1  | 02:44:02 0|app  | 2025-04-01 02:44:02: [error] App: 403: POST /api/sessions: 192.168.60.13: Invalid username or password: {"email":"jon***@gmail.com"}
joplin-1  | 02:44:02 0|app  | 2025-04-01 02:44:02: App: POST /api/sessions (403) (62ms)
joplin-1  | 02:44:02 0|app  | 2025-04-01 02:44:02: [error] App: 403: POST /api/sessions: 192.168.60.13: Invalid username or password: {"email":"jon***@gmail.com"}
joplin-1  | 02:44:02 0|app  | 2025-04-01 02:44:02: App: POST /api/sessions (403) (60ms)
```

Repro steps:

1. Have sync working properly
2. Change PW in web admin UI
3. Hit sync again, and get the error.

However, when the app goes into a loop and doesn't stop, the server logs show:

```
joplin-1  | 02:44:59 0|app  | 2025-04-01 02:44:59: [error] App: 403: POST /api/sessions: 192.168.60.13: Invalid username or password: {"email":"jon***@gmail.com"}
joplin-1  | 02:44:59 0|app  | 2025-04-01 02:44:59: App: POST /api/sessions (403) (61ms)
joplin-1  | 02:44:59 0|app  | 2025-04-01 02:44:59: [error] App: 403: POST /api/sessions: 192.168.60.13: Invalid username or password: {"email":"jon***@gmail.com"}
joplin-1  | 02:44:59 0|app  | 2025-04-01 02:44:59: App: POST /api/sessions (403) (61ms)
joplin-1  | 02:44:59 0|app  | 2025-04-01 02:44:59: [error] App: 403: POST /api/sessions: 192.168.60.13: Invalid username or password: {"email":"jon***@gmail.com"}
joplin-1  | 02:44:59 0|app  | 2025-04-01 02:44:59: App: POST /api/sessions (403) (61ms)
joplin-1  | 02:44:59 0|app  | 2025-04-01 02:44:59: [error] App: 403: POST /api/sessions: 192.168.60.13: Invalid username or password: {"email":"jon***@gmail.com"}
joplin-1  | 02:44:59 0|app  | 2025-04-01 02:44:59: App: POST /api/sessions (403) (65ms)
joplin-1  | 02:45:02 0|app  | 2025-04-01 02:45:02: [error] App: 403: POST /api/sessions: 192.168.60.13: Invalid username or password: {"email":"jon***@gmail.com"}
joplin-1  | 02:45:02 0|app  | 2025-04-01 02:45:02: App: POST /api/sessions (403) (62ms)
joplin-1  | 02:45:02 0|app  | 2025-04-01 02:45:02: [error] App: 403: POST /api/sessions: 192.168.60.13: Invalid username or password: {"email":"jon***@gmail.com"}
joplin-1  | 02:45:02 0|app  | 2025-04-01 02:45:02: App: POST /api/sessions (403) (60ms)
```

Repro steps:

1. Have sync working properly.
2. Change PW in web admin UI
3. Turn off app completely, including tray icon.
4. On app restart, sync again and we are stuck in this state.


I suspect it is a client side issue, the server responds almost identically between the 2 calls.

**Comment by laurent22** [comment]
One issue at least is that it's retrying multiple times without waiting between each requests. Is it possible that it's triggering something on your server, firewall or other mechanism that prevent DDoS?

A stuck connection usually means a server that never responds.

**Comment by jonmchan** [comment]
No, I do not believe the connection is actually stuck as evidence that other request respond properly and if you look at the server logs, they all show 60-70ms response times - everything is returning as expected. I believe it is a client issue that it is stuck in some loop.

I unfortunately don't have any more time to test, but I will try to look into over the weekend. I will try with other OSes and other computers to try to determine if it is a server or client side issue.

**Comment by laurent22** [comment]
> No, I do not believe the connection is actually stuck as evidence that other request respond properly and if you look at the server logs, they all show 60-70ms response times - everything is returning as expected

Unfortunately if a request is stuck there will be no log statement - it's only printed when it's completed

**Comment by jonmchan** [comment]
I'll go run it with [TCPView](https://learn.microsoft.com/en-us/sysinternals/downloads/tcpview) to see if the connection is still open or not over the weekend as well.

**Comment by laurent22** [comment]
Any luck with this endless sync? I haven't heard users complaining about Joplin Cloud that's why at the moment I'm thinking that may be a problem with your setup, reverse proxy or some other server component, but happy to be proven wrong.

**Comment by jonmchan** [comment]
It does endless sync on mobile as well. I am running the Joplin Server Beta behind nginx. I'm going to dive into the server side to see if there is anything wrong there. I still haven't been able to confirm the exact issue.

**Comment by jonmchan** [comment]
I have not been able to see anything suspicious on the nginx side of things. Nothing suspicious in the logs.

I disabled nginx and served joplin server beta directly to rule out anything with the nginx proxy.

My findings:

From TCPView, the network connection opens and closes within a few seconds - it does not hang at all. This corresponds with what is being seen in the logs on the server side. 

The client application is the only side that appears in a bad state (hung). I cannot cancel after it is in this hung state. 

This leads me to still conclude it is an application issue, not an issue on the server.

I confirmed this behavior in Joplin on Windows, Android, iOS, and Mac.

Here's a video showing everything.

https://www.dropbox.com/scl/fi/1mulrt927wrb4wbkyeuyw/Recording-2025-04-13-001035.mp4?rlkey=qh2ggd44jjeeq1gjp8ksthq65&st=dab2tk8u&dl=0

**Comment by jonmchan** [comment]
re: 

> I haven't heard users complaining about Joplin Cloud

This is an extremely small edge case... You have to be in a bad password state. Most people would just fix their password on the client and not even notice.

**Comment by jonmchan** [comment]
I created a brand new profile with no notebooks and the issue was gone.

Can there be anything profile specific to cause the sync to error on invalid password/403 error from server? 

My profile has 12 notebooks, dozens of tags, over 700 (600MB) resources and over 1000 notes... I can't figure out what in the world it can be, but I can very reliably recreate this issue if I am on my profile and the password is incorrect.

I have not been able to recreate this issue on a new profile. I tried adding 12 notebooks, but I would get the error message. It would not hang in the synchronization state.
