### ISSUE TITLE
Webclipper: There was some error creating the note: {"error":"Internal Server Error: Cannot read property '0' of undefined"}

### ISSUE THREAD

**Issue by CollinChaffin** [laurent22/joplin#1851]
## Environment

Joplin version: 1.0.165
Platform: Windows/Chrome
OS specifcs:

## Steps To Reproduce

1. Visit https://adamtheautomator.com/build-powershell-gui/
2. Use webclipper to save simplified page
3. Clipper does NOT report the warning exclamation that simplified may not render correctly
3. Receive code error of:  `There was some error creating the note: {"error":"Internal Server Error: Cannot read property '0' of undefined"}`

Describe what you expected to happen:

Either a proper clip, or a partial clip.

## Logfile

Was unfortunately not in debugging mode but since easy enough to reproduce wanted to report right away since outstanding dev commits haven't yet been rolled into release.  TIA!

**Comment by tessus** [comment]
@laurent22 is this fixed in git master?

**Comment by laurent22** [comment]
I don't know actually.

**Comment by tessus** [comment]
Ok, I will create a new version and then we'll see. ;-)

**Comment by tessus** [comment]
@laurent22 FYI, the error still occurs with new clipper release (1.0.18)

**Comment by CollinChaffin** [comment]
Yep @laurent22 I can confirm latest still throws it and if you need, here is another page I found that can reproduce it:

https://mountainfirefly.dev/posts/build-and-run-node-app-with-docker-compose/

Perform a simple clip and the exception is thrown.

**Comment by laurent22** [comment]
@CollinChaffin, yes I found what the issue was and fixed it. It will be part of the next desktop release.

**Comment by CollinChaffin** [comment]
LOL was just replying missed the commit.  Nice!  Thanks!
