### ISSUE TITLE
View starts at top, Edit at bottom [Android]

### ISSUE THREAD

**Issue by gitoss** [laurent22/joplin#2287]
The View mode starts at the top of the document, but when switching to Edit the cursor is at the bottom.

This might be an convenient idea, but every other text editing app I've ever encountered starts at the top or - like Word - at the last cursor position from a previous session.

What's worse, combined with #2286 it takes ages to get to the top of the document.

=> the Edit cursor position should be
a) at the current scroll position or at least at the top, and/or b) there should be an option to have Edit start at the top.

## Environment

Joplin version: 1.0.315 
Platform: Android
OS specifcs: Pie

## Steps To Reproduce

1. open notebook, open note - view starts at the top
2. click red pen circle at the bottom right - edit starts at the bottom

Describe what you expected to happen:

=> I'd expect the edit cursor to be at the current scroll position or at the top of the document.

**Comment by Neurogami** [comment]
What makes more annoying is that it's the opposite of how the desktop version behaves, where editing starts at the top.

**Comment by gitoss** [comment]
I just discovered the 'features' forum there already is a thread about it, sorry, my bad:

https://discourse.joplinapp.org/t/start-editing-at-the-top-in-mobile-app-feature-suggestion/1594

... so feel free to close this bug if this is the wrong way to track this.

**Comment by axq** [comment]
There was even work done on a pull request already:  https://github.com/laurent22/joplin/pull/2025
It's on hold for now, but the problem is real, and I'm really looking forward to a resolution.

**Comment by gitoss** [comment]
I've commented in the other/original ticket.

My 2ct is that an option "start edit at top/bottom" should be a quick and easy fix @laurent22 that could be removed once an automatic "start at current view position" can be implemented. 

This temp fix would make Joplin/mobile usable with longer documents for everyone until cursor and scrolling apis are extended. I faintly remember waiting forever for 'the framework surely will implement this asap' in some of my own past projects...

**Comment by deftdawg** [comment]
Still an issue

**Comment by Neurogami** [comment]
I'm not seeing this anymore.   Can't find anyplace in the app to know what version I'm using, but I assume it's the latest.

**Comment by deftdawg** [comment]
@Neurogami scroll to the bottom of the configuration screen to find the Android app version.  1.0327 is the lastest I have released Apr 10.

Click edit on any document longer than the screen, it will open the document for editing at the top of the document however as soon as you tap into the edit text box to bring up the keyboard you get scrolled all the way to the bottom.

**Comment by Neurogami** [comment]
version 1.0.327  
databse v28 
fts enabled : 1

And you're right.  I had clicked on the edit button, and the view stays at the top, but I hadn't actually wanted to edit anything.  I see now that when I tap again to edit at the top I suddenly get super-scrolled to the bottom.  : (

Thanks for getting me to recheck this.

Bug still exists.

**Comment by axq** [comment]
Not fixed yet, 1.0.329.

**Comment by Neurogami** [comment]
Still broken.

**Comment by Neurogami** [comment]
Still unfixed.   Still requires attention

**Comment by gitoss** [comment]
I have to admit I quit using Joplin because this is so annoying. Without proper multi-platform editing I'm sticking to good ol' .txt files and folders for the time being - but I'd be happy to return to Joplin once this is fixed.

**Comment by Retew** [comment]
Is it there any hope we are getting this fixed anytime soon? It has been 8 months now...

**Comment by kingone51** [comment]
I wonder if this problem can be solved in 2020.

**Comment by haeringer** [comment]
Please leave it open, stale bot ;)

**Comment by pymche** [comment]
Still an issue, would appreciate some attention on this!

**Comment by gitoss** [comment]
Ymmv, but no activity on this is really unfortunate because this would be fixable with a binary option to let users chose where they would like to start editing - top (without skipping and confusion) or bottom (afaik the author's preference).

It doesn't seem to require new toolkit versions or extensive coding like related issues with scrollbars https://github.com/laurent22/joplin/issues/3790 or start editing at arbitrary positions https://github.com/laurent22/joplin/issues/3790

**Comment by guzelmarmara** [comment]
Funny that such a minor improvement is not taken seriously by the developers and it has been more than a year since it was first raised.

**Comment by deftdawg** [comment]
@laurent22 please reopen, the merged patch does not address it.

**Comment by gitoss** [comment]
+1 for re-opening this pr, the behavior is still as broken as it was ever - as I just had to find out after joyfully re-installing Joplin, hoping I could use it after all on Android.

Why not add an option "Start at top/bottom"? This demonstrates the problem: https://github.com/laurent22/joplin/pull/4998#issuecomment-869199352

**Comment by laurent22** [comment]
Yes I think we can re-open this bug. @roman-r-m's fix was to allow focusing the text editor without making it scroll, and doesn't deal with switching between editor and view.

**Comment by skylercole** [comment]
Bump this issue. 
I think this is the only problem I've encountered with the software so far after the setup. 
But it is real pain, as mobile editing is practically useless for long notes. Even making it only stay at the top when editing, like the desktop client, would be a huge win.

**Comment by deftdawg** [comment]
At this point, I'd be happy with a button in the title bar or a long press option on the cut/copy menu that let me jump to the top... This issue sucks sooo bad on Android (90% of my notes are more than 1 android screen long)

Edit: one of those floating "back to the top" buttons you see on some websites would be another alternative

**Comment by romanoce** [comment]
I am opening a Github account to second this.... I am using Joplin 2.7.2 in Android. If viewer / editor switching (happiest solution) turns out to be difficult to implement, I am happy with one of the following, in descending order of happiness:
- scrollbar in editor view
- "inertia" scrolling in editor view
- a "start from top / bottom" option in configuration

**Comment by samarutuk** [comment]
Now editing starts at the top of the document in the Android App (2.11.32), but for long notes, which you want to continue on and on, this is _very bad._ I preferred the old behavior and would have liked an option where the user can decide what they need.
In a diary, for example, you continue at the end and do not want to scroll to the bottom every time. I agree with _romanoce_ and also wish **"a "start (+ edit) from top / bottom" option in configuration".**
