### ISSUE TITLE
Mobile: On the "All Notes" Page, when a note is moved to another notebook, it gets removed from "All Notes" page.

### ISSUE THREAD

**Issue by Rahulm2310** [laurent22/joplin#2770]
## Environment

Joplin version: 1.0.322
Platform: Mobile

![20200316_000833](https://user-images.githubusercontent.com/54268438/76708256-769d0000-671b-11ea-9d2d-d3e5c4ed1103.gif)

## Steps to reproduce

1. Select a note on the All Notes page.
2. Move it to another notebook.
3. It gets removed from the All Notes page.

## Describe what you expected to happen
The moved note should not remove from the All Notes page and should persist. 

I would love to pickup this issue.

**Comment by mic704b** [comment]
I think this is resolved on an old PR that was merged recently.

**Comment by mic704b** [comment]
Does the problem still exist on the latest master?

**Comment by Rahulm2310** [comment]
> Does the problem still exist on the latest master?

Yeah it does

**Comment by abhi6501** [comment]
Sorry for interrupting,I don't know whether this will help or not but just for a thought, I think the notes stay in the All notes page but not immediately after moving but if we go to the respective notebook where the note is moved and click on the All notes page again. The notes stay. (Might be a bug still.)

**Comment by Rahulm2310** [comment]
>
> I think the notes stay in the All notes page but not immediately after
> moving but if we go to the respective notebook where the note is moved and
> click on the All notes page again. The notes stay. (Might be a bug still.)
>
Ofcourse it is a bug!
That's not the desired behavior.It is annoying to go to the notebook & then
back to All Notes page just to see the moved notes again.Even if the notes
are moved, they should never be removed from the All Notes page.

>

**Comment by rossorp** [comment]
Still an issue on Android with v1.0.329
