### ISSUE TITLE
Installer removes custom tray icon on each update

### ISSUE THREAD

**Issue by pomeloy** [laurent22/joplin#4155]
## Environment

Joplin version: 1.4.16
Platform: Windows
OS specifics: 

## Steps to reproduce

1. Install Joplin using the provided Setup executable.
2. The installer removes any Joplin tray icons and re-creates a previously deleted desktop icon.

## Describe what you expected to happen

The installer should not interfere with tray icons.

**Comment by Nixellion** [comment]
I would add that it should not interfere with any changes done to the icons at all. Right now it looks like it looks for all icons that are related to Joplin and nukes them all. That's carpet bombing approach, which is very odd and imo bad by design.

I even tried making copies of icons with different names - it removes them all.

**Comment by pomeloy** [comment]
Still an issue.

**Comment by Nixellion** [comment]
Still an issue. Just installed latest version yesterday. Still removed all the joplin icons from the desktop.

**Comment by Nixellion** [comment]
Still an issue.

**Comment by pomeloy** [comment]
Still an issue.

This seems to be the problem: https://github.com/electron-userland/electron-builder/pull/5312
Should be in one of the next releases.

As for re-creating the desktop icon, this could be a workaround:
https://github.com/electron-userland/electron-builder/issues/1095#issuecomment-271135624
in
https://github.com/laurent22/joplin/blob/c1198dc76a99135c349fccf6cdecc15fe7611734/packages/app-desktop/package.json#L68

**Comment by Nixellion** [comment]
Sadly can't check up on this issue anymore as I've since moved to Chocolatey and it manages updates instead. And it does not remove the icon, but I can't tell if it's because it does the update differently or because Joplin's installer was fixed. Hopefully someone else will be able to test it.

But really, I don't think it's something about specific environment, just move icon to the tray, remove the original icon from the desktop and try to run the update. It will remove the icon from the tray and put a new one on the desktop. Well, it did. Maybe now it's fixed, I would hope :) Thanks for finally paying attention to this issue regardless! Been quiet a while.

**Comment by pomeloy** [comment]
Still an issue.

**Comment by Nixellion** [comment]
Still an issue, and actually I need to take my words about using Chocolatey being a workaround back. It does the same thing as apparently it simply runs the same installer anyway. Icons are still removed.

**Comment by egberts** [comment]
yep, still an issue.

This time, I did a fresh Github pull on a fresh install on Debian 11.2 via 'Joplin_install*.sh' script.

And the wonderful Joplin application icon is still ... *cricket*.


Details:
Joplin 2.6.10 (prod, linux)

Client ID: 0851835e2ef142558fe0810b105d16be
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: 98fba37
