### ISSUE TITLE
Plugins - Not allow updating to a non-compliant version

### ISSUE THREAD

**Issue by dpoulton-github** [laurent22/joplin#4801]
[Forum Post](https://discourse.joplinapp.org/t/improvement-plugins-not-allow-updating-to-a-non-compliant-version/16370)

Joplin 1.7.11

If a plugin is already installed and an update is available the plugins settings page will invite the user to apply that update. However if the update is not compliant with the currently installed Joplin version the update will still take place but the plugin will no longer work, requesting the user to "Please upgrade Joplin to use this plugin". This is problematic if the user is using the most current release version and the plugin only works with a pre-release. This is also possibly undesirable if for any reason the user is intentionally holding back on an earlier Joplin version.

Joplin will not allow an initial install of a non-compliant plugin and ideally users should not be able to update a plugin to a version that does not work with the installed Joplin version.

**Comment by axtyax** [comment]
Should this be split into two PR's @tessus ? One for checking `app_min_version` at initial install and another for checking on update. Or would one suffice?

**Comment by laurent22** [comment]
I believe this has been fixed in a recent version. If not, let me know.

**Comment by JackGruber** [comment]
@laurent with the version `2.0.10` it is possible to update to a plugin witch welches requird `2.1.3`.
I also found nothing in the changlogs after `2.0.10` that this was fixed. 

Therefore, I think that problem is not fixed yet, unless I have overlooked something in the changelogs.

**Comment by laurent22** [comment]
ok I think I confused this with another update related change.

**Comment by NeerajGartia21** [comment]
Is this issue still there?

**Comment by Daeraxa** [comment]
If you can still replicate it then... yes

**Comment by NeerajGartia21** [comment]
![image](https://user-images.githubusercontent.com/80708727/161429906-839075b2-8513-4bdf-af76-83a01f442ff0.png)
I was thinking to change the boolean value of the `canBeUpdatedPluginIds` state to `true` or `false` according to the installed Joplin version and the min app version required for the plugin. And thereafter I will change the plugin view.
Will it solve this issue?

**Comment by NeerajGartia21** [comment]
How can I test my implementation for this issue?

**Comment by NeerajGartia21** [comment]
![Screenshot from 2022-04-07 00-58-28](https://user-images.githubusercontent.com/80708727/162064180-6044e783-cda9-4ee4-9565-346331e54b4f.png)
Is this resolves the issue?
