### ISSUE TITLE
Web clipper not working "missing token"

### ISSUE THREAD

**Issue by df0o** [laurent22/joplin#5125]
Joplin web clipper Chrome extension gives missing token error when trying to save to notebook. Notebook dropdown also does not show any notebooks. There's also no preview displayed for any of the options. 
I have Joplin client application open and the plug in shows server status as ready. 

Using Chrome version 91.0.4472.124
Web clipper version 1.6.1

![image](https://user-images.githubusercontent.com/12823973/123554011-1e411480-d74c-11eb-95a6-83b61559960f.png)

![image](https://user-images.githubusercontent.com/12823973/123552810-e46d0f80-d745-11eb-835c-1039e4eb86f5.png)

## Environment

Joplin version: Joplin 2.1.7 (prod, win32)

Web clipper version: 1.6.1

Chrome version: Version 91.0.4472.124 (Official Build) (64-bit)

Platform: Windows

OS specifics: 
- Edition	Windows 10 Pro
- Version	21H1
- OS build	19043.1081
- Experience	Windows Feature Experience Pack 120.2212.3920.0

## Steps to reproduce

1. Open Joplin client application and enable clipper services
2. Install latest version of web clipper from Chrome extension store
3. Go to any website and click on the Joplin web clipper extension 
4. Select any of the clipping options and click confirm
5. Missing token error shows up

## Describe what you expected to happen

I expected a preview of the page being clipped to show up, and I would be able to select which notebook I want to save the clipping to. Then, when confirm is pressed, the site is clipped to the notebook. 

## Logfile

[log-clipper.txt](https://github.com/laurent22/joplin/files/6722069/log-clipper.txt)

**Comment by laurent22** [comment]
Yes sorry about that, this is because the latest version of the app is not compatible with the old version of the clipper. I've published the new clipper version to the stores but it might take a few days before they review it and release it.

**Comment by df0o** [comment]
Thanks for the quick response! Can't wait to use the clipper soon 😃

**Comment by rwperrott** [comment]
If a new release of Joplin is going to break the clipper extension, this needs noting in the release notes, and the Joplin upgrade prompt should be disabled, or at least include a clipper warning, until Joplin detects the required clipper extension version on the Mozilla and chrome extension websites. So, I'll be downgrading my copy of Joplin to resolve this puzzling disconnect.

**Comment by ahxxm** [comment]
i just upgraded from firefox store, but after `Grant authorisation`, it still says `Permission Needed`
My joplin desktop version is `v2.1.7`

**Comment by silviuvulcan** [comment]
Same here. Windows 10, Firefox, Nextcloud sync.

1. Joplin Web Clipper plugin updated and instead of the non-working one I see "Permission needed"
2. This triggers "The Web Clipper needs your authorisation..." message in Joplin
3. I click on "Grant authorisation"
4. Clipper plugin still doesn't work and triggers the Grant message again in the desktop app. ➿ 

If I should post some logs that can help just let me know.

**Comment by laurent22** [comment]
Hmm, yes looks like Firefox works differently than Chrome for this. While your grant permission in the app, the clipper popup is closed and so the process is aborted. I'll check and publish a fix as soon as posisble.

**Comment by laurent22** [comment]
Ok the fix is done and extension is published again (still need to wait for Mozilla to review). Thanks for your patience.

**Comment by silviuvulcan** [comment]
Confirmed, the new Clipper version fixed this problem and is working fine with Firefox.

**Comment by jmcastagnetto** [comment]
Confirmed that with Joplin Web Clipper extensions Chrome and Firefox under Linux (Ubuntu 24.04LTS) work again

**Comment by rwperrott** [comment]
New Clipper connected and clipped in Brave after auth. in new Joplin.

**Comment by SuperXiaoxiong** [comment]
chrome: 91.0.4472.114
Joplin Web Clipper: 2.1.2
Joplin for Desktop Joplin 1.8.5 (prod, darwin)
doesn't work , that stuck on needed permission

**Comment by fengwang** [comment]
@laurent22 Could please provide the working versions? I cannot make the web clipper work with

chromium 91.0.4472.114
Joplin Web Clipper 2.1.2
joplin-desktop 2.0.11

**Comment by laurent22** [comment]
Joplin Desktop should be 2.1.7

**Comment by laurent22** [comment]
Leaving issue open for the next few days till everybody has the right versions of clipper and desktop app.

**Comment by fengwang** [comment]
> Joplin Desktop should be 2.1.7

Many thanks for the quick reply. I confirm Joplin Desktop 2.1.7 works with Joplin Web Clipper 2.1.2 and Chromium 91.0.4472.114.

**Comment by laurent22** [comment]
Seems to be fine now.
