### ISSUE TITLE
Joplin app keeps updating all items with Joplin Server

### ISSUE THREAD

**Issue by mada199122** [laurent22/joplin#5133]
At every sync the app updates all the remote items as in the screenshot below.

![Screenshot 2021-06-30 at 09 33 54](https://user-images.githubusercontent.com/61902329/123923546-6731dc80-d989-11eb-8c80-a275dd079f9a.jpg)

-->

## Environment

Joplin version: 2.1.7
Platform: MacOS
OS specifics: Big Sur 11.4

## Steps to reproduce

1. Sync the Mac app with Joplin Server 2.1.6 

  Issues without reproduction steps are likely to stall.
-->

## Describe what you expected to happen
Sync only new item and not all every time

## Logfile

Log Joplin App MacOS
[log.txt.tar.gz](https://github.com/laurent22/joplin/files/6739043/log.txt.tar.gz)

Log Joplin Server Docker
[ebb965e23b23.log.gz](https://github.com/laurent22/joplin/files/6739027/ebb965e23b23.log.gz)

-->

**Comment by Nepochal** [comment]
The error is not limited to Mac. I habe the same issue with Joplin 2.1.7. on linux and 2.1.3 on Android.
I'm using Joplin-Server 2.1.2.

**Comment by roadbearstudios** [comment]
Same here, with Mac and Linux client versions 2.1.7 and Android 2.1.3 against Joplin-Server 2.1.6-beta.

**Comment by mada199122** [comment]
Now I solved exporting all the notes with the MacOs client, updating all the Apps to the last version available, the Server to the 2.1.6-beta and then I initialised the server deleting the database.
So I recreated everything and after that I re-imported the backup...
Now seams to work everything  fine... 
No more sync issue...

Big pain I know...

**Comment by mada199122** [comment]
you are true... I confirm...

**Comment by wrhsd1** [comment]
Same here, and I moved to Nextcloud and worked, but with low sync speed.

**Comment by KajWiik** [comment]
I can confirm these symptoms, client 2.1.7, server 2.1.6-beta, both in Ubuntu 20.04.

**Comment by laurent22** [comment]
So just to confirm, does it happen after you share a note, or after you share a notebook? (because the other report mentioned sharing notes)

**Comment by mada199122** [comment]
I can confirm you just sharing a single note it's enough for breaking the sync.
I haven't tried sharing an entire notebook.
Thanks

**Comment by roadbearstudios** [comment]
> So just to confirm, does it happen after you share a note, or after you share a notebook? (because the other report mentioned sharing notes)

In my case it went wrong immediately after upgrading the desktop-client from 2.0.11 to 2.1.7, and the 2.0.11 install already contained shared notebooks. After starting with a clean server and reuploading all notes from a jex-backup everything was fine until I shared a notebook again.

**Comment by laurent22** [comment]
Ok it should be fixed now. Thanks everyone for helping narrow down the issue, I will publish a hotfix 2.1 version soon with the fix.

**Comment by Jip-Hop** [comment]
Seems to be fixed for me on MacOS (Joplin 2.1.8) But as soon as I sync with iOS it modifies all items and the desktop clients will re-sync as well. Has an iOS update been submitted to the App Store?

**Comment by roadbearstudios** [comment]
> Seems to be fixed for me on MacOS (Joplin 2.1.8) But as soon as I sync with iOS it modifies all items and the desktop clients will re-sync as well. Has an iOS update been submitted to the App Store?

Same problem over here, everything was synced up again but the iPad started re-syncing and as a result all other devices also started re-syncing.

**Comment by mada199122** [comment]
I confirm... the iOS app still shows the bug

**Comment by W1BTR** [comment]
Anyone else still having this issue? Sharing a notebook after enabling encryption and it's syncing the whole notebook of 600+ items every time a sync starts. Joplin 3.2.13.

By the time it's done, it's time for another sync, so it's in a constant loop.

```
2025-03-31 10:15:42: Synchronizer: Sync: updateRemote: local has changes: Resource: (Local 661cbe4670ce4b84870503ab9222868e): (Remote 661cbe4670ce4b84870503ab9222868e.md)
2025-03-31 10:15:43: Synchronizer: Sync: updateRemote: local has changes: Resource: (Local 43fa0024977641f68a5bed0ab88ae043): (Remote 43fa0024977641f68a5bed0ab88ae043.md)
2025-03-31 10:15:44: Synchronizer: Sync: updateRemote: local has changes: Resource: (Local 9b00849a2bd24c7c940b8189d4b2cecf): (Remote 9b00849a2bd24c7c940b8189d4b2cecf.md)
2025-03-31 10:15:45: Synchronizer: Sync: updateRemote: local has changes: Resource: (Local cc68067f7e0245ac95bf78ff738b2431): (Remote cc68067f7e0245ac95bf78ff738b2431.md)
2025-03-31 10:15:45: Synchronizer: Sync: updateRemote: local has changes: Resource: (Local 6a9a7bd5157346319d25b2c84a232645): (Remote 6a9a7bd5157346319d25b2c84a232645.md)
2025-03-31 10:15:46: Synchronizer: Sync: updateRemote: local has changes: Resource: (Local 249b858faa1d4e42a59b4d9a128c3f88): (Remote 249b858faa1d4e42a59b4d9a128c3f88.md)
2025-03-31 10:15:47: Synchronizer: Sync: updateRemote: local has changes: Resource: (Local 37e189daf9d24109864a6ff5c6288aec): (Remote 37e189daf9d24109864a6ff5c6288aec.md)
2025-03-31 10:15:48: Synchronizer: Sync: updateRemote: local has changes: Resource: (Local 0c6d68f78c7748c2b47d8b4b89455cbf): (Remote 0c6d68f78c7748c2b47d8b4b89455cbf.md)
2025-03-31 10:15:48: Synchronizer: Sync: updateRemote: local has changes: Resource: (Local c3a06a9a7da343c6a54f05df0b79cbb4): (Remote c3a06a9a7da343c6a54f05df0b79cbb4.md)
```

**Comment by roadbearstudios** [comment]
> Anyone else still having this issue? Sharing a notebook after enabling encryption and it's syncing the whole notebook of 600+ items every time a sync starts. Joplin 3.2.13.
> 
> By the time it's done, it's time for another sync, so it's in a constant loop.
> 
> ```
> 2025-03-31 10:15:42: Synchronizer: Sync: updateRemote: local has changes: Resource: (Local 661cbe4670ce4b84870503ab9222868e): (Remote 661cbe4670ce4b84870503ab9222868e.md)
> 2025-03-31 10:15:43: Synchronizer: Sync: updateRemote: local has changes: Resource: (Local 43fa0024977641f68a5bed0ab88ae043): (Remote 43fa0024977641f68a5bed0ab88ae043.md)
> 2025-03-31 10:15:44: Synchronizer: Sync: updateRemote: local has changes: Resource: (Local 9b00849a2bd24c7c940b8189d4b2cecf): (Remote 9b00849a2bd24c7c940b8189d4b2cecf.md)
> 2025-03-31 10:15:45: Synchronizer: Sync: updateRemote: local has changes: Resource: (Local cc68067f7e0245ac95bf78ff738b2431): (Remote cc68067f7e0245ac95bf78ff738b2431.md)
> 2025-03-31 10:15:45: Synchronizer: Sync: updateRemote: local has changes: Resource: (Local 6a9a7bd5157346319d25b2c84a232645): (Remote 6a9a7bd5157346319d25b2c84a232645.md)
> 2025-03-31 10:15:46: Synchronizer: Sync: updateRemote: local has changes: Resource: (Local 249b858faa1d4e42a59b4d9a128c3f88): (Remote 249b858faa1d4e42a59b4d9a128c3f88.md)
> 2025-03-31 10:15:47: Synchronizer: Sync: updateRemote: local has changes: Resource: (Local 37e189daf9d24109864a6ff5c6288aec): (Remote 37e189daf9d24109864a6ff5c6288aec.md)
> 2025-03-31 10:15:48: Synchronizer: Sync: updateRemote: local has changes: Resource: (Local 0c6d68f78c7748c2b47d8b4b89455cbf): (Remote 0c6d68f78c7748c2b47d8b4b89455cbf.md)
> 2025-03-31 10:15:48: Synchronizer: Sync: updateRemote: local has changes: Resource: (Local c3a06a9a7da343c6a54f05df0b79cbb4): (Remote c3a06a9a7da343c6a54f05df0b79cbb4.md)
> ```

I do. I stopped using shared notebooks a while ago as it isn't trustworthy.

**Comment by W1BTR** [comment]
Looks like after the initial couple of syncs this stopped happening. Now if I could just get connections to stop timing out...
