### ISSUE TITLE
Android app sync never completes

### ISSUE THREAD

**Issue by JulesFM92** [laurent22/joplin#5858]
Hello. I've been a Joplin user for a about a year and a half, and I always experience the following problem with the mobile app:

- Joplin Version 2.6.3, Database v41
- Android 9
- Dropbox sync

Every time I have installed the mobile Joplin app, the first sync was very difficult and unreliable, no matter the device or version of the app. It either takes a very long time to complete, or stops as soon as the screen goes black. Whatever the case, the sync is eventually said to be complete, but not all my notes, tags and notebooks are retrieved or decrypted. Pushing the sync button over and over does not help. Switching between wifi and mobile connection does not make a difference. Reinstalling the app solves nothing either.

In my previous phone, somehow after a number of attempts, the synchronization actually completed and everything worked fine afterwards. Recently, in my current new phone (Asus ZenFone Max Pro M2, X01BDA), nothing helps and I can't therefore use the app.

Should I give up?

Steps to reproduce:

1. Install Joplin Mobile
2. Define the corresponding Dropbox account as the sync target
3. Add the decryption master key
4. Sync
5. Hopeless frustration

![Screenshot_20211213-215923](https://user-images.githubusercontent.com/91769729/145915754-3fbae4e0-658f-41df-b2e6-8b4e9d84e6c6.png)

**Comment by graphit0** [comment]
Hello @JulesFM92 
> It either takes a very long time to complete, or stops as soon as the screen goes black.

It's actually expected behavior, i.e. not a bug — as at the moment background sync is not implemented. Progress on the issue can be tracked in issue #3872. Before it is solved first sync may take a while and must be performed with the app in the foreground and phone screen unlocked. You may adjust your system auto-locking settings to max time system allows to make sure screen doesn't go to sleep. 

After first complete sync, there shouldn't be missing notes/tags. Can you please reinstall your app and confirm that lack of background sync is the issue?

**Comment by JackGruber** [comment]
There is also a FAQ entry for this:
https://joplinapp.org/faq/#not-all-notes-folders-or-tags-are-displayed-on-the-mobile-app

You have several options:
- Use a app to prevent sleep
- Use develop mode to disable sleep
- Connect the phone to power and set the display timeout to maximum

**Comment by JulesFM92** [comment]
I know it has been a long time, but thank you both very much, @graphit0 and @JackGruber. The problem was solved and now I know to properly sync everything at each install.

**Comment by sourcecodemage** [comment]
> I know it has been a long time, but thank you both very much, @graphit0 and @JackGruber. The problem was solved and now I know to properly sync everything at each install.

How did you solve it?

**Comment by JulesFM92** [comment]
@majorgear, I solved it by following the above recommendation of just waiting for a complete sync while the app was running in the foreground, and not letting the screen lock until it had finished.

**Comment by releve1403** [comment]
Hi there, 
About issue 3872 and this one, I just spent a couple of days trying to sync my Dropbox repository from old iOS to new Android cell phone. 
In fact, this link (https://discourse.joplinapp.org/t/cant-get-joplin-android-to-sync/14103) saves me and guided me to this issue.
I've seen that issue 3872 about background sync on mobiles is closed but the problem is still there. 
Furthermore, the help documentation about synchronisation says this :
"...the application will synchronise in the background whenever it is running, or you can click on "Synchronise" to start a synchronisation manually. Joplin will background sync automatically after any content change is made on the local application." 
This is misleading because I never thought the problem was with background sync not working, although I saw timeout error in the error log (Synchronizer: "Could not refresh lock - cancelling sync. Error was:", "Error: Lock has expired...)
At least, if the problem cannot be solved, or should I say feature implemented, it would be appreciated to modify the help documentation and give the way to sync on first attempt on a new phone.
