### ISSUE TITLE
Inconsistent highlight behavior for "find and replace" feature on mobile

### ISSUE THREAD

**Issue by b02860de585071a2** [laurent22/joplin#8893]
## Environment

Joplin version: 2.12.2
Platform: Android
OS specifics: Android 13

## Steps to reproduce

1. Open a note
2. Press "search" icon on the markdown toolbar
3. Observe highlight behavior (explained in detail below)

### To reproduce incorrect/unwanted behavior:

- Input query (no text highlighted)  
![Screenshot_20230916_125122_Joplin.png](https://github.com/laurent22/joplin/assets/96025485/61eeae1b-39d3-4d4a-ad60-cd6f64bd50e5)

- Press "enter" key or "next" icon on search toolbar (first entry *selected*, NOT *highlighted*)  
![Screenshot_20230916_125141_Joplin.png](https://github.com/laurent22/joplin/assets/96025485/df5b7a1f-232c-4c47-810d-474b2baca5f1)

- Press "enter" key or "next" icon on search toolbar to repeatedly select (NOT highlight) the next entries 

---

### To reproduce correct/desired behavior:

- Do not input anything in the search field
- Press "enter" key to submit an empty query
- After first submitting an empty query, input desired search terms (as normal). Note how results are highlighted throughout the entire document as you modify your input. 

![Screenshot_20230916_125220_Joplin.png](https://github.com/laurent22/joplin/assets/96025485/b03c3b2f-9f19-489f-91e7-d9b9555f63a8)

- Press "enter" key or "next" icon on search bar to cycle through highlighted matches in order (as normal)  

![Screenshot_20230916_125234_Joplin.png](https://github.com/laurent22/joplin/assets/96025485/37fa0123-8331-4d9f-a1dd-02c77304eb2b)

![Screenshot_20230916_125621_Joplin.png](https://github.com/laurent22/joplin/assets/96025485/ae98e6df-4d2b-4a7d-a778-4ad1ab9b9f25)

## Describe what you expected to happen

Search query matches should be highlighted through the entire document, as is the case with the desktop application. It should not be necessary to first submit an empty query. 

## Logfile

Logs for the time period in which I tested:

![Screenshot_20230916_132328_Joplin.png](https://github.com/laurent22/joplin/assets/96025485/558babfd-64b3-41ce-bed3-5be76c02e8a3)

(no errors were thrown in logcat either)

**Comment by personalizedrefrigerator** [comment]
Related:
- https://github.com/laurent22/joplin/commit/9b348fdc29dec7d21b1b4ffdcafb51950f8a8eb3 (disables highlighting selection matches)
- https://github.com/laurent22/joplin/pull/6803 **may** have fixed the bug same bug addressed by 9b348fdc29dec7d21b1b4ffdcafb51950f8a8eb3

**Comment by b02860de585071a2** [comment]
> Related:
>
>     * [9b348fd](https://github.com/laurent22/joplin/commit/9b348fdc29dec7d21b1b4ffdcafb51950f8a8eb3) (disables highlighting selection matches)

I actually tried earlier to test a build from its parent commit (https://github.com/laurent22/joplin/commit/ec97dd8c60e946eff67624bfca01665cc5472015), but kept running into versioning problems with Kotlin. 

Reversing the changes made in https://github.com/laurent22/joplin/commit/9b348fdc29dec7d21b1b4ffdcafb51950f8a8eb3 doesn't seem to solve the problem on its own.

**Comment by b02860de585071a2** [comment]
> Hey there, it looks like there has been no activity on this issue recently. Has the issue been fixed, or does it still require the community's attention? If you require support or are requesting an enhancement or feature then please create a topic on the [Joplin forum](https://discourse.joplinapp.org/). This issue may be closed if no further activity occurs. You may comment on the issue and I will leave it open. Thank you for your contributions.

.

**Comment by b02860de585071a2** [comment]
> Hey there, it looks like there has been no activity on this issue recently. Has the issue been fixed, or does it still require the community's attention? If you require support or are requesting an enhancement or feature then please create a topic on the [Joplin forum](https://discourse.joplinapp.org/). This issue may be closed if no further activity occurs. You may comment on the issue and I will leave it open. Thank you for your contributions.

.

**Comment by personalizedrefrigerator** [comment]
This may have been fixed in #9207! If so, the fix should be available in a few weeks.

**Comment by b02860de585071a2** [comment]
> This may have been fixed in #9207! If so, the fix should be available in a few weeks.

Amazing, I will report back once that update becomes available!

**Comment by b02860de585071a2** [comment]
I can confirm that this is fixed as of version 2.13.7 (2097727) from the F-Droid repo!
